# Generated by Django 5.2 on 2025-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0004_citytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
